### ISSUE TITLE
video captioning very slow?

### ISSUE THREAD

**Issue by huangjch526** [aigc-apps/EasyAnimate#104]
video captioning very slow?

**Comment by yunkchen** [comment]
Have you followed this tutorial and used VILA1.5-40b-AWQ?

**Comment by huangjch526** [comment]
> Have you followed this tutorial and used VILA1.5-40b-AWQ?
> 
> https://github.com/aigc-apps/EasyAnimate/tree/main/easyanimate/video_caption

yes，I use VILA1.5-40b-AW and follow your VILA_MODEL_PATH=/PATH/TO/VILA_MODEL REWRITE_MODEL_PATH=/PATH/TO/REWRITE_MODEL sh scripts/stage_3_video_recaptioning.sh.

I use 8 A100 80G to run this sh scripts/stage_3_video_recaptioning.sh, on a 1M subset of Panda70M. It shows that this takes me almost 70 hours, which is too slow for me. Hope you can help me, is this normal? How to make it faster?

**Comment by hkunzhe** [comment]
@huangjch526, Based on your compute resources and the amount of data, the processing time is normal. If you want to further improve the processing speed, you can try:
1. Adjust [num-video-frames](https://github.com/aigc-apps/EasyAnimate/blob/main/easyanimate/video_caption/scripts/stage_3_video_recaptioning.sh#L40) from 8 to 6 or 4, as most (90%) of the time for VILA inference is to retrieve tokens for video frames.
2. Switch VILA1.5-40b-AW to [VILA1.5-13b-AWQ](https://huggingface.co/Efficient-Large-Model/VILA1.5-13b-AWQ).
3. Adopt stricter data filtering.

Note that, Both 1 and 2 take a trade-off between recaption quality and speed.

**Comment by huangjch526** [comment]
can I use Llama-3-VILA1.5-8b-AWQ? I find that easyanimate/video_caption/scripts/stage_3_video_recaptioning.sh say "Manually download Efficient-Large-Model/Llama-3-VILA1.5-8b-AWQ to VILA_MODEL_PATH".

Will Llama-3-VILA1.5-8b-AWQ be faster than your mentioned VILA1.5-13b-AWQ?

**Comment by yunkchen** [comment]
> can I use Llama-3-VILA1.5-8b-AWQ? I find that easyanimate/video_caption/scripts/stage_3_video_recaptioning.sh say "Manually download Efficient-Large-Model/Llama-3-VILA1.5-8b-AWQ to VILA_MODEL_PATH".
> 
> Will Llama-3-VILA1.5-8b-AWQ be faster than your mentioned VILA1.5-13b-AWQ?

of cause faster
