### ISSUE TITLE
Issues when Inpainting a Video

### ISSUE THREAD

**Issue by ArlenCHEN** [aigc-apps/EasyAnimate#108]
hi @yunkchen,

I tried to use the provided trained model, e.g., 960 to do inpainting for a given video. I tried to use a fixed mask throughout the entire video, but I got pure black from the model in the target area. See the below pic (one of the frames) for an example. Can you give some suggestions?
<img width="1244" alt="lQLPJx8jkaiRTI_NBXzNCbiwevV1vJoFaHkGwMGQg81gAA_2488_1404" src="https://github.com/user-attachments/assets/163b4b4f-2c35-48cc-ab67-fa2547c2963b">

**Comment by njzxj** [comment]
Hello, I also encountered this problem when Inpainting a Video. Can you tell me how to solve it？Thank you very much
