### ISSUE TITLE
About initialization of training 

### ISSUE THREAD

**Issue by GengDavid** [aigc-apps/EasyAnimate#112]
Thanks for your great project. If I want to train EasyAnimate with my own data (e.g. Panda70M) without your pre-training, do I need to load pre-trained T2I HunYuanDiT as initialization for the transformer?

**Comment by yunkchen** [comment]
yes

**Comment by yunkchen** [comment]
> Thanks for your quick response! Could you let me know which version of HunYuanDiT is used in EasyAnimate? Thanks.

v1.0, but you could try v1.2

**Comment by GengDavid** [comment]
I'll try. Thanks again.
