### ISSUE TITLE
division by zero during training

### ISSUE THREAD

**Issue by GengDavid** [aigc-apps/EasyAnimate#113]
Thanks for your great work. I am currently training EasyAnimate with the default setting in script/train.sh. During training, there are some "division by zero" printed. It does not interrupt the training, and the loss looks normal. Is it normal to see such a warning during training? I am not sure whether I should continue my current training as it takes much time and resources to train.  
Thanks!

**Comment by yunkchen** [comment]
show your real log would be better

**Comment by GengDavid** [comment]
**Thanks for your reply.  The log looks like this:** 
<img width="705" alt="image" src="https://github.com/user-attachments/assets/a93613f7-870b-401c-8564-a085b32c501d">  

**And the progress bar looks like this:**
<img width="759" alt="image" src="https://github.com/user-attachments/assets/5f6afc00-523f-46c5-9bcb-ce0ee0a53d02">



Note that there are about 700 lines of "division by zero" (out of 25000 iterations ) printed in the console. I am not sure where this warning comes from. It is just printed rather than leading to an error.

**Comment by yunkchen** [comment]
Check your train data path, this log means some data not found.
