### ISSUE TITLE
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'

### ISSUE THREAD

**Issue by Wangzhipeng777** [aigc-apps/EasyAnimate#114]
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/opt/conda/lib/python3.8/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 34, in <module>
    from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/opt/conda/lib/python3.8/site-packages/huggingface_hub/__init__.py)

My version
accelerate               0.31.0
huggingface-hub          0.24.6
transformers             4.39.0
Trying multiple versions but still unable to import

train.sh
export MODEL_NAME="/ComfyUI/models/EasyAnimate/EasyAnimateV3-XL-2-InP-960x960"
export DATASET_NAME=""
export DATASET_META_NAME="/ComfyUI/custom_nodes/EasyAnimate/datasets/internal_datasets/json_of_internal_datasets.json"
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
NCCL_DEBUG=INFO

# When train model with multi machines, use "--config_file accelerate.yaml" instead of "--mixed_precision='bf16'".
accelerate launch --mixed_precision="bf16" scripts/train.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATASET_NAME \
  --train_data_meta=$DATASET_META_NAME \
  --config_path "/ComfyUI/custom_nodes/EasyAnimate/config/easyanimate_video_slicevae_motion_module_v3.yaml" \
  --image_sample_size=960 \
  --video_sample_size=960 \
  --token_sample_size=512 \
  --video_sample_stride=1 \
  --video_sample_n_frames=144 \
  --train_batch_size=1 \
  --video_repeat=1 \
  --gradient_accumulation_steps=1 \
  --dataloader_num_workers=8 \
  --num_train_epochs=100 \
  --checkpointing_steps=500 \
  --learning_rate=2e-05 \
  --lr_scheduler="constant_with_warmup" \
  --lr_warmup_steps=100 \
  --seed=42 \
  --output_dir="output_dir" \
  --enable_xformers_memory_efficient_attention \
  --gradient_checkpointing \
  --mixed_precision="bf16" \
  --adam_weight_decay=3e-2 \
  --adam_epsilon=1e-10 \
  --vae_mini_batch=1 \
  --max_grad_norm=0.05 \
  --random_hw_adapt \
  --training_with_video_token_length \
  --motion_sub_loss \
  --not_sigma_loss \
  --random_frame_crop \
  --enable_bucket \
  --train_mode="inpaint" \
  --trainable_modules "."

**Comment by yunkchen** [comment]
https://github.com/run-llama/llama_index/discussions/14605

**Comment by yunkchen** [comment]
If the versions are really as follows, this error would not appear
```
accelerate 0.31.0
huggingface-hub 0.24.6
transformers 4.39.0
```

**Comment by Wangzhipeng777** [comment]
> 如果版本确实如下，则不会出现此错误
> 
> ```
> accelerate 0.31.0
> huggingface-hub 0.24.6
> transformers 4.39.0
> ```
The issue has been resolved, as I am using the conda environment, the accelerate startup in the sh file requires specifying an absolute path
