### ISSUE TITLE
使用v3版本生成视频完全不相干

### ISSUE THREAD

**Issue by sugersyy** [aigc-apps/EasyAnimate#127]
你好，我使用v3版本生成视频（所有 参数都没有动过）但生成的视频与描述内容完全不相关。
![Uploading Snipaste_2024-10-28_16-20-39.png…]()

**Comment by sugersyy** [comment]
![Snipaste_2024-10-28_16-20-39](https://github.com/user-attachments/assets/0ac1e0cb-11cf-42de-8242-a283e3eb7997)
是英文，我保持了初始界面的数据进行生成

**Comment by yunkchen** [comment]
生成的分辨率太小了，960模型选择生成分辨率要满足960*960附近的

**Comment by sugersyy** [comment]
感谢！
