### ISSUE TITLE
Diff Inpaint with Control from in_channel on  v5?

### ISSUE THREAD

**Issue by xesdiny** [aigc-apps/EasyAnimate#132]
Why Inpaint use 16+1+16 ,but Control featrue( Canny,Pose,depth, etc.) after vae use 16+16?

**Comment by bubbliiiing** [comment]
Inpaint needs latents + mask + masked_pixels.
Control needs latents + control_conditions.
Control does not need mask condition.

**Comment by xesdiny** [comment]
@bubbliiiing  Is the whole process like this?


t2v -- i2v paint(use mask dim=33)
      \
        - control (dim=32）

**Comment by bubbliiiing** [comment]
Yes

> @bubbliiiing Is the whole process like this?
> 
> ```
> t2v -- i2v paint(use mask dim=33)
>       \
>        - control (dim=32）
> ···
> ```

**Comment by xesdiny** [comment]
By thy way, Compression ratio (1k -> 2k), can the data process  fps be increased  8 -> 16 fps？
