### ISSUE TITLE
EasyAnimateV5 Sampler for Text to Video ComfyUI Node Input Prompt

### ISSUE THREAD

**Issue by bagelbig** [aigc-apps/EasyAnimate#134]
The sample workflow raises an issue with the input of type 'prompt', it does not like this being linked to 'text'.

Also, I could not find any node that will link to this 'prompt' (even nodes that state they have a 'prompt' output).

**Comment by bubbliiiing** [comment]
Fixed in https://github.com/aigc-apps/EasyAnimate/pull/141, please redownload the json.
