### ISSUE TITLE
Exception in ComfyUI nodes for v5:  cannot access local variable 'videos' where it is not associated with a value

### ISSUE THREAD

**Issue by throttlekitty** [aigc-apps/EasyAnimate#137]
I get this after the video has finished sampling.

> 100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:09<00:00,  1.97s/it]
> !!! Exception during processing !!! cannot access local variable 'videos' where it is not associated with a value
> Traceback (most recent call last):
>   File "H:\AI\ComfyUI\ComfyUI\execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "H:\AI\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "H:\AI\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "H:\AI\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "H:\AI\ComfyUI\ComfyUI\custom_nodes\EasyAnimate\comfyui\comfyui_nodes.py", line 648, in process
>     return (videos,)
>          ^^^^^^
> UnboundLocalError: cannot access local variable 'videos' where it is not associated with a value

**Comment by bubbliiiing** [comment]
Fixed in https://github.com/aigc-apps/EasyAnimate/pull/140
