### ISSUE TITLE
运行生成视频代码，如何修改GPU位置

### ISSUE THREAD

**Issue by JuntongWang** [aigc-apps/EasyAnimate#156]
我在运行生成视频的代码时，经常运行到一半提示超出显存，我有空余的GPU，但是我修改了很多地方的GPU使用序号，报错仍然显示在GPU0的位置上，我想知道该如何修改使用GPU的位置

**Comment by yunkchen** [comment]
```
export CUDA_VISIBLE_DEVICES=1
```
可以让推理跑在卡1上，推理只能用单卡。

**Comment by JuntongWang** [comment]
> ```
> export CUDA_VISIBLE_DEVICES=1
> ```
> 
> 可以让推理跑在卡1上，推理只能用单卡。

好的，成功了，谢谢您！
