### ISSUE TITLE
v5 model t2v generates error by gradio

### ISSUE THREAD

**Issue by sunshinewhy** [aigc-apps/EasyAnimate#162]
using the gradio test t2v, the console outputs the error:
/EasyAnimate# python app.py 
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/usr/local/lib/python3.10/dist-packages/gradio/components/dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: none or set allow_custom_value=True.
  warnings.warn(
/EasyAnimate/easyanimate/ui/ui.py:811: GradioUnusedKwargWarning: You have unused kwarg parameters in Image, please remove them: {'sources': 'upload'}
  start_image = gr.Image(
/EasyAnimate/easyanimate/ui/ui.py:838: GradioUnusedKwargWarning: You have unused kwarg parameters in Image, please remove them: {'sources': 'upload'}
  end_image   = gr.Image(label="The image at the ending of the video (图片到视频的结束图片[非必需, Optional])", show_label=False, elem_id="i2v_end", sources="upload", type="filepath")
/EasyAnimate/easyanimate/ui/ui.py:842: GradioUnusedKwargWarning: You have unused kwarg parameters in Video, please remove them: {'sources': 'upload'}
  validation_video = gr.Video(
/EasyAnimate/easyanimate/ui/ui.py:853: GradioUnusedKwargWarning: You have unused kwarg parameters in Image, please remove them: {'sources': 'upload'}
  validation_video_mask = gr.Image(
/EasyAnimate/easyanimate/ui/ui.py:865: GradioUnusedKwargWarning: You have unused kwarg parameters in Video, please remove them: {'sources': 'upload'}
  control_video = gr.Video(
/usr/local/lib/python3.10/dist-packages/gradio/utils.py:812: UserWarning: Expected 2 arguments for function <function ui.<locals>.upload_generation_method at 0x7fc2bb35e290>, received 1.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/gradio/utils.py:816: UserWarning: Expected at least 2 arguments for function <function ui.<locals>.upload_generation_method at 0x7fc2bb35e290>, received 1.
  warnings.warn(
Running on local URL:  http://0.0.0.0:1173

To create a public link, set `share=True` in `launch()`.
Update diffusion transformer
The config attributes {'sample_size': 256} were passed to AutoencoderKLMagvit, but are not expected and will be ignored. Please verify your config.json configuration file.
### unexpected keys: 0;
[] []
loaded 3D transformer's pretrained weights from 
/EasyAnimate/models/Diffusion_Transformer/EasyAnimateV5-12b-zh-InP/transformer ...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:20<00:00, 10.43s/it]
The config attributes {'snr_shift_scale': 1.0} were passed to EulerDiscreteScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 1421.87it/s]
You have disabled the safety checker for <class 'easyanimate.pipeline.pipeline_easyanimate_multi_text_encoder_inpaint.EasyAnimatePipeline_Multi_Text_Encoder_Inpaint'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Update diffusion transformer done
The config attributes {'snr_shift_scale': 1.0} were passed to DDIMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
You may ignore this warning if your `pad_token_id` (0) is identical to the `bos_token_id` (0), `eos_token_id` (2), or the `sep_token_id` (None), and your input is not padded.
/EasyAnimate/easyanimate/pipeline/pipeline_easyanimate_multi_text_encoder_inpaint.py:1054: FutureWarning: Accessing config attribute `enable_clip_in_inpaint` directly via 'EasyAnimateTransformer3DModel' object attribute is deprecated. Please access 'enable_clip_in_inpaint' over 'EasyAnimateTransformer3DModel's config object instead, e.g. 'unet.config.enable_clip_in_inpaint'.
  elif clip_image is None and num_channels_transformer != num_channels_latents and self.transformer.enable_clip_in_inpaint:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [03:33<00:00,  4.28s/it]
Killed

pip list packages:
Package Version Editable project location

absl-py 2.1.0
accelerate 1.1.1
aiofiles 23.2.1
aiohappyeyeballs 2.4.3
aiohttp 3.10.10
aiosignal 1.3.1
albucore 0.0.20
albumentations 1.4.21
allspark 0.15.0
altair 5.4.1
annotated-types 0.7.0
antlr4-python3-runtime 4.9.3
anyio 4.6.2.post1
asttokens 2.4.1
async-timeout 4.0.3
attrs 24.2.0
av 13.1.0
beautifulsoup4 4.12.3
bitsandbytes 0.44.1
blinker 1.4
came-pytorch 0.1.3
causal-conv1d 1.4.0
certifi 2024.8.30
charset-normalizer 3.4.0
click 8.1.7
clip 1.0
cloudpickle 3.1.0
comm 0.2.2
contourpy 1.3.1
cryptography 3.4.8
cycler 0.12.1
datasets 3.1.0
dbus-python 1.2.18
debugpy 1.8.8
decorator 5.1.1
decord 0.6.0
deepspeed 0.15.4
diffusers 0.31.0
dill 0.3.8
diskcache 5.6.3
distro 1.7.0
distro-info 1.1+ubuntu0.2
docker-pycreds 0.4.0
easyocr 1.7.1
einops 0.8.0
eval_type_backport 0.2.0
exceptiongroup 1.2.2
executing 2.1.0
fastapi 0.115.4
ffmpy 0.4.0
filelock 3.13.1
flash-attn 2.6.3
fonttools 4.54.1
frozenlist 1.5.0
fsspec 2024.2.0
ftfy 6.3.1
func_timeout 4.3.5
gguf 0.10.0
gitdb 4.0.11
GitPython 3.1.32
gradio 3.48.0
gradio_client 0.6.1
grpcio 1.67.1
h11 0.14.0
hjson 3.1.0
httpcore 1.0.6
httplib2 0.20.2
httptools 0.6.4
httpx 0.27.2
huggingface-hub 0.26.2
idna 3.10
imageio 2.36.0
imageio-ffmpeg 0.5.1
importlib-metadata 4.6.4
importlib_resources 6.4.5
interegular 0.3.3
ipykernel 6.29.5
ipython 8.29.0
jedi 0.19.2
jeepney 0.7.1
Jinja2 3.1.3
jiter 0.7.0
joblib 1.4.2
jsonschema 4.23.0
jsonschema-specifications 2024.10.1
jupyter_client 8.6.3
jupyter_core 5.7.2
keyring 23.5.0
kiwisolver 1.4.7
lark 1.2.2
launchpadlib 1.10.16
lazr.restfulclient 0.14.4
lazr.uri 1.0.6
lazy_loader 0.4
lightning-utilities 0.11.8
llvmlite 0.43.0
lm-format-enforcer 0.10.6
mamba-ssm 2.2.2
Markdown 3.7
MarkupSafe 2.1.5
matplotlib 3.9.2
matplotlib-inline 0.1.7
mistral_common 1.4.4
more-itertools 8.10.0
mpmath 1.3.0
msgpack 1.1.0
msgspec 0.18.6
multidict 6.1.0
multiprocess 0.70.16
narwhals 1.13.4
natsort 8.4.0
nest-asyncio 1.6.0
networkx 3.2.1
ninja 1.11.1.1
numba 0.60.0
numpy 1.26.3
nvidia-cublas-cu11 11.11.3.6
nvidia-cuda-cupti-cu11 11.8.87
nvidia-cuda-nvrtc-cu11 11.8.89
nvidia-cuda-runtime-cu11 11.8.89
nvidia-cudnn-cu11 9.1.0.70
nvidia-cufft-cu11 10.9.0.58
nvidia-curand-cu11 10.3.0.86
nvidia-cusolver-cu11 11.4.1.48
nvidia-cusparse-cu11 11.7.5.86
nvidia-ml-py 12.560.30
nvidia-nccl-cu11 2.20.5
nvidia-nvtx-cu11 11.8.86
oauthlib 3.2.0
omegaconf 2.3.0
openai 1.54.3
opencv-python 4.10.0.84
opencv-python-headless 4.10.0.84
orjson 3.10.11
outlines 0.0.46
packaging 24.2
pandas 2.2.3
parso 0.8.4
partial-json-parser 0.2.1.1.post4
pexpect 4.9.0
pillow 10.4.0
pip 24.2
platformdirs 4.3.6
prometheus_client 0.21.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit 3.0.48
propcache 0.2.0
protobuf 5.28.2
psutil 6.0.0
ptyprocess 0.7.0
pure_eval 0.2.3
py-cpuinfo 9.0.0
pyairports 2.1.1
pyarrow 18.0.0
pyclipper 1.3.0.post6
pycountry 24.6.1
pydantic 2.9.2
pydantic_core 2.23.4
pydub 0.25.1
Pygments 2.18.0
PyGObject 3.42.1
PyJWT 2.3.0
pyparsing 2.4.7
python-apt 2.4.0+ubuntu4
python-bidi 0.6.3
python-dateutil 2.9.0.post0
python-dotenv 1.0.1
python-multipart 0.0.17
pytorch-lightning 1.9.4
pytz 2024.2
PyYAML 6.0.2
pyzmq 26.2.0
ray 2.38.0
referencing 0.35.1
regex 2024.11.6
requests 2.32.3
rpds-py 0.21.0
safetensors 0.4.5
scenedetect 0.6.4
scikit-image 0.24.0
scipy 1.14.1
SecretStorage 3.3.1
semantic-version 2.10.0
sentencepiece 0.2.0
sentry-sdk 2.16.0
setproctitle 1.3.3
setuptools 75.1.0
shapely 2.0.6
simsimd 6.0.5
six 1.16.0
smmap 5.0.1
sniffio 1.3.1
soupsieve 2.6
stack-data 0.6.3
starlette 0.41.2
stringzilla 3.10.10
sympy 1.12
taming-transformers 0.0.1 /root/src/taming-transformers
tensorboard 2.18.0
tensorboard-data-server 0.7.2
tifffile 2024.9.20
tiktoken 0.7.0
timm 1.0.11
tokenizers 0.20.3
tomesd 0.1.3
torch 2.4.0+cu118
torchaudio 2.4.0+cu118
torchdiffeq 0.2.4
torchmetrics 1.5.2
torchsde 0.2.6
torchvision 0.19.0+cu118
tornado 6.4.1
tqdm 4.66.5
traitlets 5.14.3
trampoline 0.1.2
transformers 4.46.2
triton 3.0.0
typing_extensions 4.12.2
tzdata 2024.2
unattended-upgrades 0.1
urllib3 2.2.3
uvicorn 0.32.0
uvloop 0.21.0
vllm 0.6.3
wadllib 1.3.6
wandb 0.18.3
watchfiles 0.24.0
wcwidth 0.2.13
websockets 11.0.3
Werkzeug 3.1.3
wheel 0.37.1
xformers 0.0.27.post2+cu118
xxhash 3.5.0
yarl 1.17.1
zipp 1.0.0

**Comment by sunshinewhy** [comment]
pip list packages:
Package                           Version            Editable project location
--------------------------------- ------------------ -----------------------------
absl-py                           2.1.0
accelerate                        1.1.1
aiofiles                          23.2.1
aiohappyeyeballs                  2.4.3
aiohttp                           3.10.10
aiosignal                         1.3.1
albucore                          0.0.20
albumentations                    1.4.21
allspark                          0.15.0
altair                            5.4.1
annotated-types                   0.7.0
antlr4-python3-runtime            4.9.3
anyio                             4.6.2.post1
asttokens                         2.4.1
async-timeout                     4.0.3
attrs                             24.2.0
av                                13.1.0
beautifulsoup4                    4.12.3
bitsandbytes                      0.44.1
blinker                           1.4
came-pytorch                      0.1.3
causal-conv1d                     1.4.0
certifi                           2024.8.30
charset-normalizer                3.4.0
click                             8.1.7
clip                              1.0
cloudpickle                       3.1.0
comm                              0.2.2
contourpy                         1.3.1
cryptography                      3.4.8
cycler                            0.12.1
datasets                          3.1.0
dbus-python                       1.2.18
debugpy                           1.8.8
decorator                         5.1.1
decord                            0.6.0
deepspeed                         0.15.4
diffusers                         0.31.0
dill                              0.3.8
diskcache                         5.6.3
distro                            1.7.0
distro-info                       1.1+ubuntu0.2
docker-pycreds                    0.4.0
easyocr                           1.7.1
einops                            0.8.0
eval_type_backport                0.2.0
exceptiongroup                    1.2.2
executing                         2.1.0
fastapi                           0.115.4
ffmpy                             0.4.0
filelock                          3.13.1
flash-attn                        2.6.3
fonttools                         4.54.1
frozenlist                        1.5.0
fsspec                            2024.2.0
ftfy                              6.3.1
func_timeout                      4.3.5
gguf                              0.10.0
gitdb                             4.0.11
GitPython                         3.1.32
gradio                            3.48.0
gradio_client                     0.6.1
grpcio                            1.67.1
h11                               0.14.0
hjson                             3.1.0
httpcore                          1.0.6
httplib2                          0.20.2
httptools                         0.6.4
httpx                             0.27.2
huggingface-hub                   0.26.2
idna                              3.10
imageio                           2.36.0
imageio-ffmpeg                    0.5.1
importlib-metadata                4.6.4
importlib_resources               6.4.5
interegular                       0.3.3
ipykernel                         6.29.5
ipython                           8.29.0
jedi                              0.19.2
jeepney                           0.7.1
Jinja2                            3.1.3
jiter                             0.7.0
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2024.10.1
jupyter_client                    8.6.3
jupyter_core                      5.7.2
keyring                           23.5.0
kiwisolver                        1.4.7
lark                              1.2.2
launchpadlib                      1.10.16
lazr.restfulclient                0.14.4
lazr.uri                          1.0.6
lazy_loader                       0.4
lightning-utilities               0.11.8
llvmlite                          0.43.0
lm-format-enforcer                0.10.6
mamba-ssm                         2.2.2
Markdown                          3.7
MarkupSafe                        2.1.5
matplotlib                        3.9.2
matplotlib-inline                 0.1.7
mistral_common                    1.4.4
more-itertools                    8.10.0
mpmath                            1.3.0
msgpack                           1.1.0
msgspec                           0.18.6
multidict                         6.1.0
multiprocess                      0.70.16
narwhals                          1.13.4
natsort                           8.4.0
nest-asyncio                      1.6.0
networkx                          3.2.1
ninja                             1.11.1.1
numba                             0.60.0
numpy                             1.26.3
nvidia-cublas-cu11                11.11.3.6
nvidia-cuda-cupti-cu11            11.8.87
nvidia-cuda-nvrtc-cu11            11.8.89
nvidia-cuda-runtime-cu11          11.8.89
nvidia-cudnn-cu11                 9.1.0.70
nvidia-cufft-cu11                 10.9.0.58
nvidia-curand-cu11                10.3.0.86
nvidia-cusolver-cu11              11.4.1.48
nvidia-cusparse-cu11              11.7.5.86
nvidia-ml-py                      12.560.30
nvidia-nccl-cu11                  2.20.5
nvidia-nvtx-cu11                  11.8.86
oauthlib                          3.2.0
omegaconf                         2.3.0
openai                            1.54.3
opencv-python                     4.10.0.84
opencv-python-headless            4.10.0.84
orjson                            3.10.11
outlines                          0.0.46
packaging                         24.2
pandas                            2.2.3
parso                             0.8.4
partial-json-parser               0.2.1.1.post4
pexpect                           4.9.0
pillow                            10.4.0
pip                               24.2
platformdirs                      4.3.6
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit                    3.0.48
propcache                         0.2.0
protobuf                          5.28.2
psutil                            6.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           18.0.0
pyclipper                         1.3.0.post6
pycountry                         24.6.1
pydantic                          2.9.2
pydantic_core                     2.23.4
pydub                             0.25.1
Pygments                          2.18.0
PyGObject                         3.42.1
PyJWT                             2.3.0
pyparsing                         2.4.7
python-apt                        2.4.0+ubuntu4
python-bidi                       0.6.3
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-multipart                  0.0.17
pytorch-lightning                 1.9.4
pytz                              2024.2
PyYAML                            6.0.2
pyzmq                             26.2.0
ray                               2.38.0
referencing                       0.35.1
regex                             2024.11.6
requests                          2.32.3
rpds-py                           0.21.0
safetensors                       0.4.5
scenedetect                       0.6.4
scikit-image                      0.24.0
scipy                             1.14.1
SecretStorage                     3.3.1
semantic-version                  2.10.0
sentencepiece                     0.2.0
sentry-sdk                        2.16.0
setproctitle                      1.3.3
setuptools                        75.1.0
shapely                           2.0.6
simsimd                           6.0.5
six                               1.16.0
smmap                             5.0.1
sniffio                           1.3.1
soupsieve                         2.6
stack-data                        0.6.3
starlette                         0.41.2
stringzilla                       3.10.10
sympy                             1.12
taming-transformers               0.0.1              /root/src/taming-transformers
tensorboard                       2.18.0
tensorboard-data-server           0.7.2
tifffile                          2024.9.20
tiktoken                          0.7.0
timm                              1.0.11
tokenizers                        0.20.3
tomesd                            0.1.3
torch                             2.4.0+cu118
torchaudio                        2.4.0+cu118
torchdiffeq                       0.2.4
torchmetrics                      1.5.2
torchsde                          0.2.6
torchvision                       0.19.0+cu118
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
trampoline                        0.1.2
transformers                      4.46.2
triton                            3.0.0
typing_extensions                 4.12.2
tzdata                            2024.2
unattended-upgrades               0.1
urllib3                           2.2.3
uvicorn                           0.32.0
uvloop                            0.21.0
vllm                              0.6.3
wadllib                           1.3.6
wandb                             0.18.3
watchfiles                        0.24.0
wcwidth                           0.2.13
websockets                        11.0.3
Werkzeug                          3.1.3
wheel                             0.37.1
xformers                          0.0.27.post2+cu118
xxhash                            3.5.0
yarl                              1.17.1
zipp                              1.0.0

**Comment by yunkchen** [comment]
最终生成失败了么？
没有看到报错
