### ISSUE TITLE
Bug: The video_folder is joined to video_path multiple times in compute_semantic_consistency.py

### ISSUE THREAD

**Issue by LiuWeijunAntihos** [aigc-apps/EasyAnimate#163]
In line 133 of compute_semantic_consistency.py, video_folder is joined to video_path, and then again in line 43 of video_dataset.py, video_folder is joined to video_path.

**Comment by hkunzhe** [comment]
> In line 133 of compute_semantic_consistency.py, video_folder is joined to video_path, and then again in line 43 of video_dataset.py, video_folder is joined to video_path.

Hi, thanks for reporting it. I'll fix it ASAP.

**Comment by hkunzhe** [comment]
@LiuWeijunAntihos In fact, joining two absolute paths does not result in a bug. If you use relative paths and nested folders, it could indeed cause an error. We have supported nested folder in video_caption and fix it in https://github.com/aigc-apps/EasyAnimate/pull/165.
