### ISSUE TITLE
这项工作是复现了哪一篇论文啊

### ISSUE THREAD

**Issue by renyuanzhe** [aigc-apps/EasyAnimate#26]
还是一个全新的工作？

**Comment by ozawaoy6** [comment]
https://arxiv.org/pdf/2405.18991

**Comment by renyuanzhe** [comment]
> https://arxiv.org/pdf/2405.18991

请问是在什么数据集上训练的呀，能提供数据集的下载链接吗

**Comment by yunkchen** [comment]
> > https://arxiv.org/pdf/2405.18991
> 
> 请问是在什么数据集上训练的呀，能提供数据集的下载链接吗

数据集有一部分是我们自己内部收集的，目前没有release数据集的计划。
