### ISSUE TITLE
 Motion Amplitude (运动幅度）

### ISSUE THREAD

**Issue by yunyangge** [aigc-apps/EasyAnimate#28]
Nice work! Thanks for your codebase!
I will use this code as a codebase to train my new work.
Now I have a question:
I have noticed that the motion amplitude generated by this version of the Motion Module is not very large. Could the author inform us if there are plans to release a new Motion Module in the future?
我注意到这版的Motion Module生成的结果运动幅度都不是很大，请问作者未来是否有发布新的Motion Module的计划？

**Comment by Vincento-Wang** [comment]
> Nice work! Thanks for your codebase! I will use this code as a codebase to train my new work. Now I have a question: I have noticed that the motion amplitude generated by this version of the Motion Module is not very large. Could the author inform us if there are plans to release a new Motion Module in the future? 我注意到这版的Motion Module生成的结果运动幅度都不是很大，请问作者未来是否有发布新的Motion Module的计划？

I try the model v4， same problem, I suggested, but they refused， persist that there is no problem.
