### ISSUE TITLE
V3 model in_channels

### ISSUE THREAD

**Issue by zhang-yige** [aigc-apps/EasyAnimate#43]
For the V3 model, "in_channels": 12. 
I wonder what pre-processing has been done to latents(hidden_states in model) to match the model dimensions?
Thank you for your work!

**Comment by yunkchen** [comment]
[image guidance](https://i-blog.csdnimg.cn/direct/90303ea29db5439c8c42072ba4900e86.jpeg#pic_center)
More details: https://blog.csdn.net/weixin_44791964/article/details/140025591

**Comment by zhang-yige** [comment]
> ![image](https://private-user-images.githubusercontent.com/13468042/346771938-1809d8e9-7bec-4e94-a573-bab5aad9b20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTgxNDYsIm5iZiI6MTcyMDU5Nzg0NiwicGF0aCI6Ii8xMzQ2ODA0Mi8zNDY3NzE5MzgtMTgwOWQ4ZTktN2JlYy00ZTk0LWE1NzMtYmFiNWFhZDliMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA3NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MjU2MDI3MzU2ZmM5NDJhYjhlNjQ5ZGQzZGRjYjZiNWU0ZTI5OWJkODc2MmI3N2ZiYWM4M2ViMzNmNDk0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3l1mWLMuSDxDnpSWq00DcJQviRlyMYGrUsEnDb-WpPs)
> 
> More details: https://blog.csdn.net/weixin_44791964/article/details/140025591

OK thks
