### ISSUE TITLE
no found 'accelerate.yaml'

### ISSUE THREAD

**Issue by clumsynope** [aigc-apps/EasyAnimate#59]
When train model with multi machines, use "--config_file accelerate.yaml" instead of "--mixed_precision='bf16'". But I cannot found accelerate.yaml. Could you provide this file, thank you. @bubbliiiing @yunkchen

**Comment by bubbliiiing** [comment]
try this:
accelerate launch --mixed_precision="bf16" --main_process_ip=$MASTER_ADDR --main_process_port=$MASTER_PORT --num_machines=$WORLD_SIZE --num_processes=$NUM_PROCESS --machine_rank=$RANK scripts/train.py

**Comment by bubbliiiing** [comment]
Sometimes YAML files are not very convenient

**Comment by clumsynope** [comment]
It fixed my problems. thanks.

**Comment by huangjch526** [comment]
Where are these $MASTER_ADDR and $MASTER_PORT?

**Comment by yunkchen** [comment]
> It fixed my problems. thanks.

https://huggingface.co/docs/transformers/main/zh/main_classes/deepspeed
