### ISSUE TITLE
为什么出的视频是全黑的？

### ISSUE THREAD

**Issue by pyoliu** [aigc-apps/EasyAnimate#65]
![afc47b8e3a0b98518a7406471236847](https://github.com/user-attachments/assets/ee184efc-ef36-4848-a800-a584dafc612a)

**Comment by yunkchen** [comment]
看不出原因，需要贴一下后台的日志，要么等一会会看是否视频会加载出来。

**Comment by pyoliu** [comment]
> 看不出原因，需要贴一下后台的日志，要么等一会会看是否视频会加载出来。

### missing keys: 0; 
### unexpected keys: 96;
[] ['loss.discriminator.main.0.bias', 'loss.discriminator.main.0.weight', 'loss.discriminator.main.11.bias', 'loss.discriminator.main.11.weight', 'loss.discriminator.main.2.weight', 'loss.discriminator.main.3.bias', 'loss.discriminator.main.3.num_batches_tracked', 'loss.discriminator.main.3.running_mean', 'loss.discriminator.main.3.running_var', 'loss.discriminator.main.3.weight', 'loss.discriminator.main.5.weight', 'loss.discriminator.main.6.bias', 'loss.discriminator.main.6.num_batches_tracked', 'loss.discriminator.main.6.running_mean', 'loss.discriminator.main.6.running_var', 'loss.discriminator.main.6.weight', 'loss.discriminator.main.8.weight', 'loss.discriminator.main.9.bias', 'loss.discriminator.main.9.num_batches_tracked', 'loss.discriminator.main.9.running_mean', 'loss.discriminator.main.9.running_var', 'loss.discriminator.main.9.weight', 'loss.discriminator3d.blocks.0.conv1.bias', 'loss.discriminator3d.blocks.0.conv1.weight', 'loss.discriminator3d.blocks.0.conv2.bias', 'loss.discriminator3d.blocks.0.conv2.weight', 'loss.discriminator3d.blocks.0.downsampler.filt', 'loss.discriminator3d.blocks.0.norm1.bias', 'loss.discriminator3d.blocks.0.norm1.weight', 'loss.discriminator3d.blocks.0.norm2.bias', 'loss.discriminator3d.blocks.0.norm2.weight', 'loss.discriminator3d.blocks.0.shortcut.0.filt', 'loss.discriminator3d.blocks.0.shortcut.1.bias', 'loss.discriminator3d.blocks.0.shortcut.1.weight', 'loss.discriminator3d.blocks.1.conv1.bias', 'loss.discriminator3d.blocks.1.conv1.weight', 'loss.discriminator3d.blocks.1.conv2.bias', 'loss.discriminator3d.blocks.1.conv2.weight', 'loss.discriminator3d.blocks.1.downsampler.filt', 'loss.discriminator3d.blocks.1.norm1.bias', 'loss.discriminator3d.blocks.1.norm1.weight', 'loss.discriminator3d.blocks.1.norm2.bias', 'loss.discriminator3d.blocks.1.norm2.weight', 'loss.discriminator3d.blocks.1.shortcut.0.filt', 'loss.discriminator3d.blocks.1.shortcut.1.bias', 'loss.discriminator3d.blocks.1.shortcut.1.weight', 'loss.discriminator3d.blocks.2.conv1.bias', 'loss.discriminator3d.blocks.2.conv1.weight', 'loss.discriminator3d.blocks.2.conv2.bias', 'loss.discriminator3d.blocks.2.conv2.weight', 'loss.discriminator3d.blocks.2.norm1.bias', 'loss.discriminator3d.blocks.2.norm1.weight', 'loss.discriminator3d.blocks.2.norm2.bias', 'loss.discriminator3d.blocks.2.norm2.weight', 'loss.discriminator3d.blocks.2.shortcut.0.bias', 'loss.discriminator3d.blocks.2.shortcut.0.weight', 'loss.discriminator3d.conv_in.bias', 'loss.discriminator3d.conv_in.weight', 'loss.discriminator3d.conv_norm_out.bias', 'loss.discriminator3d.conv_norm_out.weight', 'loss.discriminator3d.conv_out.bias', 'loss.discriminator3d.conv_out.weight', 'loss.logvar', 'loss.perceptual_loss.lin0.model.1.weight', 'loss.perceptual_loss.lin1.model.1.weight', 'loss.perceptual_loss.lin2.model.1.weight', 'loss.perceptual_loss.lin3.model.1.weight', 'loss.perceptual_loss.lin4.model.1.weight', 'loss.perceptual_loss.net.slice1.0.bias', 'loss.perceptual_loss.net.slice1.0.weight', 'loss.perceptual_loss.net.slice1.2.bias', 'loss.perceptual_loss.net.slice1.2.weight', 'loss.perceptual_loss.net.slice2.5.bias', 'loss.perceptual_loss.net.slice2.5.weight', 'loss.perceptual_loss.net.slice2.7.bias', 'loss.perceptual_loss.net.slice2.7.weight', 'loss.perceptual_loss.net.slice3.10.bias', 'loss.perceptual_loss.net.slice3.10.weight', 'loss.perceptual_loss.net.slice3.12.bias', 'loss.perceptual_loss.net.slice3.12.weight', 'loss.perceptual_loss.net.slice3.14.bias', 'loss.perceptual_loss.net.slice3.14.weight', 'loss.perceptual_loss.net.slice4.17.bias', 'loss.perceptual_loss.net.slice4.17.weight', 'loss.perceptual_loss.net.slice4.19.bias', 'loss.perceptual_loss.net.slice4.19.weight', 'loss.perceptual_loss.net.slice4.21.bias', 'loss.perceptual_loss.net.slice4.21.weight', 'loss.perceptual_loss.net.slice5.24.bias', 'loss.perceptual_loss.net.slice5.24.weight', 'loss.perceptual_loss.net.slice5.26.bias', 'loss.perceptual_loss.net.slice5.26.weight', 'loss.perceptual_loss.net.slice5.28.bias', 'loss.perceptual_loss.net.slice5.28.weight', 'loss.perceptual_loss.scaling_layer.scale', 'loss.perceptual_loss.scaling_layer.shift']
Load Sampler.
Load Transformer.
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 4400, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to Transformer3DModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.99it/s]
Loading pipeline components...:  40%|█████████████████████████▏                                     | 2/5 [00:01<00:01,  1.95it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.58it/s]
  0%|                                                                                                      | 0/25 [00:00<?, ?it/s]/home/ubuntu/miniconda3/envs/sd-webui/lib/python3.10/site-packages/diffusers/models/attention.py:661: FutureWarning: `scale` is deprecated and will be removed in version 1.0.0. The `scale` argument is deprecated and will be ignored. Please remove it, as passing it will raise an error in the future. `scale` should directly be passed while calling the underlying pipeline component i.e., via `cross_attention_kwargs`.
  deprecate("scale", "1.0.0", deprecation_message)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [04:26<00:00, 10.64s/it]
/home/ubuntu/16T/smx/ComfyUI_sd3/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py:101: RuntimeWarning: invalid value encountered in cast
  return tensor_to_int(tensor, 8).astype(np.uint8)
Prompt executed in 374.79 seconds

这个是日志，然后我想问一下，我文生图生成的视频质量也很不好，图像人脸都会扭曲，是因为参数设置的原因嘛？

**Comment by yunkchen** [comment]
日志看起来是生成成功了，你可以可以看看文件夹里有没有生成的视频，应该只是浏览器上没显示出来；
会发生扭曲，需要优化提示词，如果是图生视频，尽可能选择人脸背景干净一些的、动感的照片

**Comment by pyoliu** [comment]
> 日志看起来是生成成功了，你可以可以看看文件夹里有没有生成的视频，应该只是浏览器上没显示出来； 会发生扭曲，需要优化提示词，如果是图生视频，尽可能选择人脸背景干净一些的、动感的照片

好的我去试试，我刚刚直接从easyanimate sample for image to video节点预览了图像，发现是从生成图像的时候就变黑了~

**Comment by bubbliiiing** [comment]
请使用bf16，fp16会有nan的问题

**Comment by ivankxt** [comment]
> 请使用bf16，fp16会有nan的问题

同样出现视频全黑的问题，因为用T4跑，不支持bf16，所以改成fp16跑，请问fp16会有nan的问题有什么解决方法？Allocated 

memory: memory=5.812 GB
Max allocated memory: max_memory=14.054 GB
Max reserved memory: max_reserved=14.625 GB

/home/engine/custom_nodes/ComfyUI-VideoHelperSuite-main/videohelpersuite/nodes.py:104: RuntimeWarning: invalid value encountered in cast
  return tensor_to_int(tensor, 8).astype(np.uint8)
Prompt executed in 608.98 seconds
