### ISSUE TITLE
Video VAE

### ISSUE THREAD

**Issue by Limingxing00** [aigc-apps/EasyAnimate#70]
Hi,

Thank you for the good work. 

I am interested in the vae part. I have some problems.
1、The paper show "we initialize the weight of Slice VAE from the aforementioned MagViT trained above.". But to the best of my knowledge, MagViT didn't release model weight.
2、Refer to table 1, did you only use image data to train 3d VAE? This makes me very confused. What video data did you use to train the 3D VAE?
3、Did you use the magvit method to train the 3D VAE?

**Comment by yunkchen** [comment]
1. 'We initially trained MagViT using the Adam optimizerwith beta values of (0.5, 0.9) and a learningrate of 1e-4, for a total of 350,000 training steps.', We have trained MagViT by ourself.
2. there is misread, that 'VAE adaption' not means training Slice VAE, while it means connecting Slice VAE and Video Diffusion Transformer at first time which needs only images to adapt.

**Comment by Limingxing00** [comment]
Thank you for the reply!
