### ISSUE TITLE
关于长视频生成的重叠长度

### ISSUE THREAD

**Issue by ldqrecord** [aigc-apps/EasyAnimate#76]
![image](https://github.com/user-attachments/assets/cfd305f6-a662-44cf-9fa1-64b5d2f2b01d)
请问这个参数作用是什么，不同条件有什么区别

**Comment by yunkchen** [comment]
长视频生成的原理是多次生成视频然后拼接，后一段视频生成会将前一段视频的末尾几帧作为参考。
这个参数就代表上一段会有多少帧作为下一段视频的参考，越多生成的长视频连贯性、一致性越好。

**Comment by ldqrecord** [comment]
感谢，明白了
