### ISSUE TITLE
训练数据格式问题

### ISSUE THREAD

**Issue by windIsMyHeart** [aigc-apps/EasyAnimate#78]
你好，我训练用的是绝对路径，训练数据分布在不同的位置，也要整理成下面这种形式吗？
📦 project/
├── 📂 datasets/
│   ├── 📂 internal_datasets/
│       ├── 📂 videos/
│       │   ├── 📄 00000001.mp4
│       │   ├── 📄 00000001.jpg
│       │   └── 📄 .....
│       └── 📄 json_of_internal_datasets.json
现在训练在数据加载时会报错：
![image](https://github.com/user-attachments/assets/d293c437-8fb4-47a0-8205-eea823310bd9)

**Comment by yunkchen** [comment]
分布在不同位置的话，应该填写绝对路径就可以训练；
日志里的报错也不一定是数据位置导致的，有更完整的日志么？

**Comment by windIsMyHeart** [comment]
> 分布在不同位置的话，应该填写绝对路径就可以训练； 日志里的报错也不一定是数据位置导致的，有更完整的日志么？

多谢回复，我刚更新了报错的截图，看起来只有在数据加载这块有报错。

**Comment by yunkchen** [comment]
> > 分布在不同位置的话，应该填写绝对路径就可以训练； 日志里的报错也不一定是数据位置导致的，有更完整的日志么？
> 
> 多谢回复，我刚更新了报错的截图，看起来只有在数据加载这块有报错。

最后一句话后面应该还有报错的日志的

**Comment by windIsMyHeart** [comment]
> > > 分布在不同位置的话，应该填写绝对路径就可以训练； 日志里的报错也不一定是数据位置导致的，有更完整的日志么？
> > 
> > 
> > 多谢回复，我刚更新了报错的截图，看起来只有在数据加载这块有报错。
> 
> 最后一句话后面应该还有报错的日志的
已补充
![image](https://github.com/user-attachments/assets/782855b0-a7a1-4e32-9c9e-57bf75c209d2)

**Comment by yunkchen** [comment]
需要检查下json里的数据路径，是不是都是正确的

**Comment by windIsMyHeart** [comment]
> 需要检查下json里的数据路径，是不是都是正确的

确认了问题，是因为dataloader_num_workers设置过大，多谢解答
