### ISSUE TITLE
模型Finetune生成结果变花屏。

### ISSUE THREAD

**Issue by windIsMyHeart** [aigc-apps/EasyAnimate#81]
你好，我处理了30w视频clip调用train.sh进行finetune训练，32卡训练了2.6kiter，在推理时候替换了512x512部分的transformers模型，在调用gradio infer的时候生成的视频都有很强的花屏现象，感觉是训练哪里出现了bug问题，能帮忙确认一下吗？
![image](https://github.com/user-attachments/assets/5fac41f5-ac15-4511-a9f0-a93eeaf91991)
以下是训练loss：
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/af9991e5-988f-4b2a-8e7e-67e44a684c9b">

**Comment by yunkchen** [comment]
生成的分辨率选择的是多少？先选择生成图片试一试，只能一步步排查

**Comment by windIsMyHeart** [comment]
> 生成的分辨率选择的是多少？先选择生成图片试一试，只能一步步排查

分辨率跟finetune模型保持一致都是512x512，图片生成也是这种问题，
1. 上面的loss跟官方finetune到最后阶段的loss能对得上吗？
2. 如果训练loss对得上，正常finetune情况下，只要不是训练的很垃圾感觉更像是推理时候的问题，基于gradio推理时候直接替换512x512 里面的transformer这种替换transformer直接infer的方式会不会有问题？
![image](https://github.com/user-attachments/assets/cca41904-30b7-4c79-b7a0-6f9902acd0a6)

**Comment by yunkchen** [comment]
应该是训崩了，可以贴一下tensorboard；
大数据的finetune v3目前并不稳定，可以试试减少些数据只训练个LoRA

**Comment by windIsMyHeart** [comment]
> 应该是训崩了，可以贴一下tensorboard； 大数据的finetune v3目前并不稳定，可以试试减少些数据只训练个LoRA
想问下训练不稳定的原因大概是什么呢？有没修复计划呀。
Lora数据量级多少比较合适呢，image和video最好都加一些？
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/b5a20841-49ed-447c-bb10-aced81b41cf8">

**Comment by yunkchen** [comment]
> > 应该是训崩了，可以贴一下tensorboard； 大数据的finetune v3目前并不稳定，可以试试减少些数据只训练个LoRA
> > 想问下训练不稳定的原因大概是什么呢？有没修复计划呀。
> > Lora数据量级多少比较合适呢，image和video最好都加一些？
> 
> <img alt="image" width="1260" src="https://private-user-images.githubusercontent.com/20079097/352937207-b5a20841-49ed-447c-bb10-aced81b41cf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzU2ODAsIm5iZiI6MTcyMjIzNTM4MCwicGF0aCI6Ii8yMDA3OTA5Ny8zNTI5MzcyMDctYjVhMjA4NDEtNDllZC00NDdjLWJiMTAtYWNlZDgxYjQxY2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA2NDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YjUzOTk2MDNkOTViZmE0M2Q1MTM1YzIzZGQyMjYzZWVmYmJmZGVhNDZlODBhYmU4ZDE1OWFjNWM4OWE4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4LeKUnr83daUtjIgbcNmrvvql4FOyQ_sFIo2pCRxLI0">

Lora的话总量小几千就很够了

**Comment by yunkchen** [comment]
调大batch size同时调小learning rate可以解决这个训崩的问题

**Comment by windIsMyHeart** [comment]
> 调大batch size同时调小learning rate可以解决这个训崩的问题

多谢解答，我去试试。还有个，我在跑video_caption分支的发现有文件应该是漏传了：EasyAnimate_video_caption/easyanimate/video_caption/vila_caption_video.py", line 33, in <module>
    from utils.filter import filter
ModuleNotFoundError: No module named 'utils.filter'

**Comment by hkunzhe** [comment]
> > 调大batch size同时调小learning rate可以解决这个训崩的问题
> 
> 多谢解答，我去试试。还有个，我在跑video_caption分支的发现有文件应该是漏传了：EasyAnimate_video_caption/easyanimate/video_caption/vila_caption_video.py", line 33, in from utils.filter import filter ModuleNotFoundError: No module named 'utils.filter'

Hi, we have updated the video_caption branch.
