### ISSUE TITLE
The Resolution of generated videos

### ISSUE THREAD

**Issue by burnquiet** [aigc-apps/EasyAnimate#84]
Thanks for your great work👍
I tried to generate some videos of different resolutions, including [256, 256], [320, 512], [320, 320] and also [384, 672].
When i use [256, 256],  the model fails to generate meaningful contents.
![256](https://github.com/user-attachments/assets/80b33402-9b8a-484c-a16d-11950a401e98)
And results of [320, 512], [320, 320] is of poor quality...🥲
Is this owing to the model is eventually finetuned on the high resolution data?

**Comment by yunkchen** [comment]
Cause of model architecture, if you using 768*768 model, the resolution you generate should height*width == 768*768.

**Comment by burnquiet** [comment]
I used 512x512 model. (And 384*672 works well)
Is there any distinct differences in the models? The configs of these three DIT seems same...
(Sorry if i missed something🥲)
