### ISSUE TITLE
使用官方的示例图片和prompt，768的模型生成720x1280视频，效果差，和官方效果对不齐

### ISSUE THREAD

**Issue by haoxurt** [aigc-apps/EasyAnimate#86]
使用论文中的示例图片和 prompt  a beautiful woman with long hair and a dress blowing in the wind, 下载768的模型，就修改了尺寸，发现效果很差。请问需要调整什么参数？ 还是说官方的demo需要用960的模型

https://github.com/user-attachments/assets/cccb19fe-6df1-44bd-be76-401eb684dd5f

**Comment by bubbliiiing** [comment]
960x960是总分辨率，768模型应该是576x1008，ui中提供了resize with length

**Comment by yunkchen** [comment]
尺寸选择“Resize to the start image”，然后Base Resolution of Pretrained Models选择768

**Comment by haoxurt** [comment]
@yunkchen @bubbliiiing 我没有用ui，我试用的是predict_i2v.py的代码，只修改了model_name和samplesize，请问还需要修改哪些地方？  
<img width="828" alt="image" src="https://github.com/user-attachments/assets/303459ce-6ef7-4662-a20c-89c53c47729b">

**Comment by yunkchen** [comment]
720*1280 > 768*768，根据这个参考图的宽高比算一下，保持总像素是768*768
效果会好很多，如果还有略微瑕疵就是调整一下seed

**Comment by haoxurt** [comment]
@yunkchen 感谢指导，现在效果基本可以了
